name: Gatsby Publish

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: action/checkout@v1
        uses: enriikke/gatsby-gh-page-action@v2

        with:
          access-token: ${{secrets.ACCESS_TOKEN}}
         deploy-branch: gh-pages
